-- Iftakhar Husan

-------------------------------------------------------------------------

-- 1 - Insert two new rows for SALARIES table:
--      3500 euros for employee 10
--      3300 euros for employee 20
-- solve 1
INSERT INTO SALARIES(EMPLOYEE, SALARY) VALUES(10, 3500);
INSERT INTO SALARIES(EMPLOYEE, SALARY) VALUES(20, 3300);
-- solve 2
INSERT INTO SALARIES(EMPLOYEE, SALARY) VALUES(20, 3300), (10, 3500);


-- 2 - Change the salary for employee 20 so that it will be 3600 euros.
UPDATE SALARIES SET SALARY=3600 WHERE EMPLOYEE=20;


-- 3 - Create a new table called SALARYHISTORY with similar structure as SALARY table.
-- solve 1
CREATE TABLE SALARYHISTORY LIKE SALARIES;
-- solve 2
CREATE TABLE SALARYHISTORY AS (SELECT * FROM SALARIES WHERE FALSE);
-- solve 3
CREATE TABLE SALARYHISTORY AS (SELECT * FROM SALARIES); -- will also copy data from SALARIES
-- solve 4
CREATE TABLE SALARYHISTORY(
    SALARYID INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL,
    SALARY DECIMAL(10, 2) NOT NULL,
    EMPLOYEE DECIMAL(3,0) NOT NULL,
    FROMDATE DATE DEFAULT CAST(NOW() AS DATE),

    PRIMARY KEY (SALARYID),
    CONSTRAINT FK_SALARYHISTORY_EMPS_EMPNUM FOREIGN KEY(EMPLOYEE)
        REFERENCES EMPS(EMPNUM)
        ON UPDATE CASCADE
        ON DELETE NO ACTION);


-- 4 - Copy the content of SALARY table to SALARYHISTORY with one query.
INSERT INTO SALARYHISTORY SELECT * FROM SALARIES;


-- 5 - Remove the salary information of employee 20 from SALARY and SALARYHISTORY tables.
-- solve 1
START TRANSACTION;
    DELETE FROM SALARIES WHERE EMPLOYEE = 20;
    DELETE FROM SALARYHISTORY WHERE EMPLOYEE = 20;
COMMIT;

-- solve 2
BEGIN;
    DELETE FROM SALARIES WHERE EMPLOYEE = 20;
    DELETE FROM SALARYHISTORY WHERE EMPLOYEE = 20;
COMMIT;

-- solve 3
    DELETE FROM SALARIES WHERE EMPLOYEE = 20;
    DELETE FROM SALARYHISTORY WHERE EMPLOYEE = 20;

-- solve 4
DELETE s, sh FROM SALARIES AS s
	INNER JOIN SALARYHISTORY AS sh 
    ON s.EMPLOYEE = sh.EMPLOYEE 
	WHERE s.EMPLOYEE = 20;

-- solve 5
DELETE s, sh FROM SALARIES AS s, SALARYHISTORY as sh
	WHERE s.EMPLOYEE = 20 and sh.EMPLOYEE = 20;
